name: Deploy Python App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Log in to Azure using OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9F30B32A715D4FCC8C90139A8CC791E0 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B1BA5CD33E5B4FCF95F5096136773A23 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6116444646614564B4B4D6C792C07789 }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'cursoaz104drfssddd'